{
    "name": "Project Task Checklist",
    "version": "16.0.1.0.0",
    "category": "Project/Project",
    "summary": "To Manage the checklists in Project's tasks",
    "author": "BizzAppDev",
    "website": "https://www.bizzappdev.com",
    "depends": ["project"],
    "data": [
        "security/ir.model.access.csv",
        "views/task_checklist_views.xml",
        "views/checklist_item_views.xml",
        "views/project_task_view.xml",
        "views/checklist_menu_view.xml",
    ],
    "license": "LGPL-3",
    "installable": True,
    "application": False,
    "auto_install": False,
}
